### ISSUE TITLE
Avoid Closure cfunctions

### ISSUE THREAD

**Issue by eschnett** [JuliaGtk/Gtk4.jl#95]
Gtk4.jl uses [Closure cfunctions](https://docs.julialang.org/en/v1/manual/calling-c-and-fortran-code/index.html#Closure-cfunctions) internally. These do not work on all architectures, e.g. they don't work on ARM, i.e. modern Apple laptops.

I see that there are two uses for closure cfunctions in the code:
````
gtype.jl:411:        deref = cfunction_(gc_unref_weak, Nothing, (Ref{typeof(x)},))
signals.jl:15:    callback = cfunction_(cb, RT, tuple(Ptr{GObject}, param_types..., Ref{CT}))
```

The first (in `gtype.jl`) always calls `gc_unref_weak` and thus doesn't need to be a closure at all, a regular cfunction would do.

The second (in `signals.jl`) does not need to be a closure either. The API has an additional argument `data` (see https://docs.gtk.org/gobject/func.signal_connect_data.html) that can be used to pass in additional information.

If changed, the exported function `cfunction_`, which always creates a closure cfunction, could be removed.

**Comment by jwahlstrand** [comment]
I think the issue goes much deeper; I count 189 total uses of `@cfunction` in this package.

**Comment by eschnett** [comment]
`@cfunction` itself is fine. The problem is when `@cfunction` is used with a `$` sign on its first argument. That happens only in a few cases, and I think all these cases are wrapped in calls to `cfunction_`. I tried converting the code, but I'm not familiar with the `GObject` and `gc_ref` stuff, so I gave up.

(The Gtk4 tests fail on my laptop, that's how I noticed.)

By the way, Github actions now support running on ARM macOS hardware for testing, e.g. via
```
jobs:
  test:
    name: Julia ${{matrix.version}} - ${{matrix.os}} - ${{matrix.arch}} - ${{github.event_name}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # See <https://julialang-s3.julialang.org/bin/versions.json> for available Julia versions
        include:
          - arch: "arm64"
            os: "macOS-14"
            version: "1.11"
```
This would allow testing Gtk4 on ARM hardware.
